# This is a config for PPIO Sandbox template.
# You can use template ID (ua5dafuizpdphs23s4qt) or template name (aprog-base-glm) to create a sandbox:

# Python SDK
# from ppio_sandbox.core import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("aprog-base-glm") # Sync sandbox
# sandbox = await AsyncSandbox.create("aprog-base-glm") # Async sandbox

# JS SDK
# import { Sandbox } from 'ppio-sandbox'
# const sandbox = await Sandbox.create('aprog-base-glm')

dockerfile = "ppio.Dockerfile"
template_name = "aprog-base-glm"
template_id = "ua5dafuizpdphs23s4qt"
